### ISSUE TITLE
Restrict Acrylic Area

### ISSUE THREAD

**Issue by nikeee** [23phy/ewc#10]
Is it possible to set a region for the blur? I imagine blurring the entire window background an then painting over it could drain some batteries.

**Comment by 23phy** [comment]
Currently nope, you cannot do that, but what you can is to enable the effect you want when the window gets focused with:
```javascript
mainWindow.on('focus', () => ewc.setAcrylic(mainWindow, 0x80000000));
```  
and to disable the effect when the window gets blurred like so.. 
```javascript
mainWindow.on('blur', () => ewc.disableComposition(mainWindow));
```

I was thinking about this, as it's limited to, well... just this, there may be a way to use [UWP/WinRT methods](https://github.com/NodeRT/NodeRT/issues/62) to to make it more "featured", it's something I'm looking into.

**Comment by nikeee** [comment]
Ok, thanks!
