### ISSUE TITLE
Laggy acrylic

### ISSUE THREAD

**Issue by Sourtoast** [23phy/ewc#16]
Hi, after launching example moving window with acrylic effect on causes huge lag for window

**Comment by 23phy** [comment]
Need more info on that, you can start with your environment, your way of applying the acrylic on the window, and if possible a code snippets of even an example. Thank you, will leave this open.

**Comment by Sourtoast** [comment]
My node version is 12.4.0 and electron 5.0.4
I've used your cloned repository and ran electron example. The only thing I changed is that I  added 
```
   webPreferences: {
      nodeIntegration: true
   }
```
To main BrowserWindow. Here is video showing what happen (sorry for the watermark) https://youtu.be/EiiNA7keyko In the video a real cursor is always shown however I don't see it until i release left mouse button

**Comment by 23phy** [comment]
Wow, that's weird indeed, I'll try to replicate that when I am on a windows system, there are high chances it won't happen on my end. The same behavior also happened to me the past few days when moving an Outlook window, not related to this repo or anything else.

**Comment by IgnusG** [comment]
This is most [likely this windows bug](https://github.com/riverar/sample-win32-acrylicblur/issues/2) introduced in a previous build. Resolved as of build [18917](https://aka.ms/AA4pzyf)

**Comment by 23phy** [comment]
I am on 17763(1809), I tried to replicate it with no success. If it's a Windows bug I think this can be closed now.

**Comment by Sourtoast** [comment]
Sure thanks for your time. I'll be waiting for the Windows update 😁

**Comment by 23phy** [comment]
Awesome, thanks for pointing out the bug. I'm going to close this issue now.
