### ISSUE TITLE
Problems with acrylic in battery saver mode

### ISSUE THREAD

**Issue by Toby56** [23phy/ewc#23]
One possibly fixable issue with the acrylic effect is that, when Windows is in **battery saver mode**, changing **to acrylic mode** (`ewc.setAcrylic`) from any other transparency mode including blur behind and transparent gradient gives a broken, fully transparent window.

So enabling acrylic from a disabled state works, but if you set it to blur behind, and then to acrylic, it breaks and you just get a fully clear window.

This only happens in battery saver mode, probably because acrylic is meant to be globally disabled in this mode to save battery.

I don't know, but maybe this can be fixed, because you can get acrylic working in battery saver mode by disabling and re-enabling again, but this produces a flicker. I ran into this issue when solving the laggy drag issue by disabling acrylic on drag. Hopefully maybe it can be fixed because it is annoying the hell out of me!

**Comment by 23phy** [comment]
It surely can be fixed, but currently I don't have the time to work on this repo, but I'll gladly approve any PR that comes regarding this issue. As you can see.. this repo hasn't been updated for like a year or so, I'll try to make some time to work on this after I deal with these crappy Windows updates.
