### ISSUE TITLE
Acrylic on elements 

### ISSUE THREAD

**Issue by FerVillanuevas** [23phy/ewc#3]
Hi bro, is possible add acrylic to HTML elements like divs, Navs, etc.?

**Comment by 23phy** [comment]
Hello @FerVillanuevas,

That's not possible, as this is using Windows APIs and it's for background of the app window. But using CSS, you might want to take a look at [this](https://stackoverflow.com/questions/44522299/css-only-acrylic-material-from-fluent-design-system).

Regards,
Oliver
