### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by DevCubeHD** [23phy/ewc#5]
![image](https://user-images.githubusercontent.com/10380127/44058470-7a5055da-9f4e-11e8-9107-27930f072258.png)

Is this caused by electron-acrylic? tried reinstalling phyton, etc, etc.. nothing worked out yet

**Comment by 23phy** [comment]
What python version are you using? I recommend 2.7

**Comment by 23phy** [comment]
Use Python 2.7 to build the module.
